-- User API Keys Table
CREATE TABLE IF NOT EXISTS user_api_keys (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL COMMENT 'Key Name',
    access_key VARCHAR(64) NOT NULL UNIQUE COMMENT 'Access Key',
    status TINYINT DEFAULT 1 COMMENT '1:Active 0:Revoked',
    last_used_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
